### ISSUE TITLE
TypeError: Cannot read property 'include' of null (sailsjs)

### ISSUE THREAD

**Issue by daithi-coombes** [tehsis/normalize#2]
When trying to run:

``` javascript
        const normalize = require('normalize');
        const result = normalize('Königsallee 37');
```

I'm getting the following...

``` bash
Wed, 08 Jun 2016 09:35:29 GMT OMG! uncaughtException: Cannot read property 'include' of null
TypeError: Cannot read property 'include' of null
    at /node_modules/normalize/lib/normalize.js:34:10
    at cb (/node_modules/winston/lib/winston/logger.js:195:7)
    at /node_modules/winston/node_modules/async/lib/async.js:119:25
    at /node_modules/winston/node_modules/async/lib/async.js:24:16
    at /node_modules/winston/lib/winston/logger.js:182:9
    at /node_modules/winston/lib/winston/transports/file.js:173:7
    at doNTCallback0 (node.js:430:9)
    at process._tickDomainCallback (node.js:400:13)
```

env

``` bash
node v5.1.1
sails v0.12.3
ubuntu 16.04 kernel 4.4.0-22-generic
```

**Comment by tehsis** [comment]
This is a different package. (instructions on README.md have been updated)

Thanks!
